// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { University } from "./University";

export type Claims = {
  id: string;
  role: Role;
  university: University;
  exp: number;
};
