// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Competition =
  | "conception_senior"
  | "conception_junior"
  | "debats_oratoires"
  | "reingenierie"
  | "genie_conseil"
  | "communication_scientifique"
  | "programmation"
  | "conception_innovatrice"
  | "cycle_superieur"
  | "none";
