// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Competition } from "./Competition";
import type { Role } from "./Role";

export type ParticipantPreview = {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  role: Role;
  competition: Competition;
  contain_cv: boolean;
};
