// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Competition } from "./Competition";
import type { DietaryRestriction } from "./DietaryRestriction";
import type { Role } from "./Role";
import type { TshirtSize } from "./TshirtSize";
import type { University } from "./University";

export type ParticipantInfo = {
  first_name: string | null;
  last_name: string | null;
  email: string | null;
  role: Role | null;
  food_forms_completed: boolean | null;
  competition: Competition | null;
  university: University | null;
  medical_conditions: string | null;
  allergies: string | null;
  pronouns: string | null;
  supper: string | null;
  phone_number: string | null;
  tshirt_size: TshirtSize | null;
  comments: string | null;
  dietary_restrictions: DietaryRestriction | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  emergency_contact_relationship: string | null;
  has_monthly_opus_card: boolean | null;
  reduced_mobility: string | null;
  study_proof: File;
  photo: File;
  cv: File;
};
