// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type University =
  | "uqac"
  | "uqar"
  | "uqat"
  | "uqo"
  | "uqtr"
  | "mcgill"
  | "mcgill_macdonald"
  | "concordia"
  | "ets"
  | "polymtl"
  | "ulaval"
  | "ulaval_agriculture"
  | "uds"
  | "none";
