services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=mamanningham@cqi-qec.qc.ca" # change this to your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend-cqi:
    image: registry.git.step.polymtl.ca/lemark/cqi-qec2025:main
    ports:
      - "3000:3000"
    labels:
      - "traefik.http.routers.backend-cqi.rule=Host(`api.cqi-qec.qc.ca`)" # Put the URL here
      - "traefik.http.services.backend-cqi.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend-cqi.entrypoints=websecure"
      - "traefik.http.routers.backend-cqi.tls.certresolver=myresolver"
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
    networks:
      - database_bridge
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_bridge
volumes:
  postgres_data:
networks:
  database_bridge:
    driver: bridge
