const YEAR = "2026";
const FIRST_DAY_COMPETITION = "15";
const LAST_DAY_COMPETITION = "18";
const EDITION_NUMBER = "41";
const QUANTITY_DELEGATIONS = 14;
const QUANTITY_UNIVERSITIES = 11;

export default {
    YEAR,
    FIRST_DAY_COMPETITION,
    LAST_DAY_COMPETITION,
    EDITION_NUMBER,
    QUANTITY_UNIVERSITIES,
    QUANTITY_DELEGATIONS,
}
