const YEAR = "2027";
const FIRST_DAY_COMPETITION = "14";
const LAST_DAY_COMPETITION = "17";
const EDITION_NUMBER = "42";
const QUANTITY_DELEGATIONS = 14;
const QUANTITY_UNIVERSITIES = 12;

export default {
    YEAR,
    FIRST_DAY_COMPETITION,
    LAST_DAY_COMPETITION,
    EDITION_NUMBER,
    QUANTITY_UNIVERSITIES,
    QUANTITY_DELEGATIONS,
}
